/**
 * Centralized permission code constants matching the Permission table codes
 * used in the seed (prisma/seed/00-permissions.ts).
 */
export const PermissionCode = {
  // Company & Users
  COMPANY_READ: 'COMPANY_READ',
  COMPANY_WRITE: 'COMPANY_WRITE',
  COMPANY_DELETE: 'COMPANY_DELETE',
  COMPANY_STAFF_MANAGE: 'COMPANY_STAFF_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE',

  // Machinery
  MACHINERY_READ: 'MACHINERY_READ',
  MACHINERY_WRITE: 'MACHINERY_WRITE',
  MACHINERY_DELETE: 'MACHINERY_DELETE',
  MACHINERY_OPERATE: 'MACHINERY_OPERATE',
  MACHINERY_MAINTAIN: 'MACHINERY_MAINTAIN',

  // Store & Inventory
  STORE_READ: 'STORE_READ',
  STORE_WRITE: 'STORE_WRITE',
  STORE_DELETE: 'STORE_DELETE',
  STORE_TRANSACTION: 'STORE_TRANSACTION',
  STORE_REQUEST_CREATE: 'STORE_REQUEST_CREATE',
  STORE_REQUEST_APPROVE: 'STORE_REQUEST_APPROVE',
  STORE_REQUEST_ISSUE: 'STORE_REQUEST_ISSUE',
  STORE_MANAGE: 'STORE_MANAGE',
  STORE_TRANSFER_REQUEST: 'STORE_TRANSFER_REQUEST',
  STORE_TRANSFER_APPROVE: 'STORE_TRANSFER_APPROVE',
  STORE_TRANSFER_COMPLETE: 'STORE_TRANSFER_COMPLETE',

  // Sales
  SALES_READ: 'SALES_READ',
  SALES_WRITE: 'SALES_WRITE',
  CUSTOMER_MANAGE: 'CUSTOMER_MANAGE',

  // Purchases
  PURCHASES_READ: 'PURCHASES_READ',
  PURCHASES_WRITE: 'PURCHASES_WRITE',
  SUPPLIER_MANAGE: 'SUPPLIER_MANAGE',

  // Finance
  FINANCE_INCOME_READ: 'FINANCE_INCOME_READ',
  FINANCE_INCOME_WRITE: 'FINANCE_INCOME_WRITE',
  FINANCE_EXPENSE_READ: 'FINANCE_EXPENSE_READ',
  FINANCE_EXPENSE_WRITE: 'FINANCE_EXPENSE_WRITE',

  // Projects & HR
  PROJECTS_READ: 'PROJECTS_READ',
  PROJECTS_WRITE: 'PROJECTS_WRITE',
  PROJECTS_DELETE: 'PROJECTS_DELETE',
  EMPLOYEES_MANAGE: 'EMPLOYEES_MANAGE',

  // Attendance
  ATTENDANCE_READ: 'ATTENDANCE_READ',
  ATTENDANCE_WRITE: 'ATTENDANCE_WRITE',

  // Timesheets
  TIMESHEET_SUBMIT: 'TIMESHEET_SUBMIT',
  TIMESHEET_APPROVE: 'TIMESHEET_APPROVE',

  // Payroll
  PAYROLL_MANAGE: 'PAYROLL_MANAGE',

  // Reports
  REPORTS_VIEW: 'REPORTS_VIEW',
  REPORTS_EXPORT: 'REPORTS_EXPORT',

  // Chart of Accounts
  ACCOUNTS_READ: 'ACCOUNTS_READ',
  ACCOUNTS_WRITE: 'ACCOUNTS_WRITE',

  // General Ledger
  LEDGER_READ: 'LEDGER_READ',
  LEDGER_POST: 'LEDGER_POST',

  // Leave Management
  LEAVE_TYPE_MANAGE: 'LEAVE_TYPE_MANAGE',
  LEAVE_REQUEST_CREATE: 'LEAVE_REQUEST_CREATE',
  LEAVE_REQUEST_APPROVE: 'LEAVE_REQUEST_APPROVE',
  LEAVE_BALANCE_VIEW: 'LEAVE_BALANCE_VIEW',

  // Tax & Payroll
  TAX_TABLE_MANAGE: 'TAX_TABLE_MANAGE',
  PAYSLIP_VIEW: 'PAYSLIP_VIEW',

  // Asset Depreciation
  DEPRECIATION_MANAGE: 'DEPRECIATION_MANAGE',
  DEPRECIATION_VIEW: 'DEPRECIATION_VIEW',
} as const;

export type PermissionCode =
  (typeof PermissionCode)[keyof typeof PermissionCode];
