import { create } from "zustand";
import { persist } from "zustand/middleware";

type Lang = "en" | "am";

interface LangState {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Layout & Nav
    "nav.dashboard": "Dashboard",
    "nav.personal": "Personal Finance",
    "nav.companies": "Companies",
    "nav.notifications": "Notifications",
    "nav.logout": "Sign Out",
    "nav.overview": "Overview",
    "nav.incomes": "Incomes",
    "nav.expenses": "Expenses",
    "nav.staff": "Staff",
    "nav.employees": "Employees",
    "nav.projects": "Projects",
    "nav.machineries": "Machineries",
    "nav.store": "Store",
    "nav.reports": "Reports",
    "header.welcome": "Welcome",

    // Login
    "login.title": "FinSync",
    "login.subtitle": "Sign in to your account",
    "login.email": "Email address",
    "login.password": "Password",
    "login.submit": "Sign in",
    "login.loading": "Signing in...",
    "login.noAccount": "Don't have an account? Register",
    "login.welcomeBack": "Welcome back!",
    "login.failed": "Login failed",

    // Register
    "register.title": "Create Owner Account",
    "register.subtitle": "Start managing your life and business",
    "register.name": "Full Name",
    "register.email": "Email address",
    "register.password": "Password",
    "register.submit": "Register",
    "register.loading": "Creating...",
    "register.haveAccount": "Already have an account? Sign in",
    "register.success": "Account created successfully!",
    "register.failed": "Registration failed",

    // Landing
    "landing.title": "FinSync App Running!",
    "landing.subtitle": "If you see this, rendering is working.",
    "landing.goLogin": "Go to Login",

    // Dashboard Overview
    "overview.title": "Overview",
    "overview.personalFinance": "Personal Finance",
    "overview.personalDesc":
      "Track your daily budgets, expenses, and savings goals.",
    "overview.goPersonal": "Go to Personal Finance →",
    "overview.businessOps": "Business Operations",
    "overview.businessDesc": "Manage companies, staff, incomes, and expenses.",
    "overview.goCompanies": "Manage Companies →",
    "overview.yourTasks": "Your Tasks",
    "overview.staffWelcome":
      "Welcome staff member! Use the menu to navigate your assigned tasks.",

    // Personal Hub
    "personal.title": "Personal Finance",
    "personal.quickAdd": "Quick Add Transaction",
    "personal.amount": "Amount ($)",
    "personal.category": "Category",
    "personal.account": "Account",
    "personal.note": "Note (Optional)",
    "personal.addExpense": "Add as Expense",
    "personal.addIncome": "Add as Income",
    "personal.budgets": "Budgets",
    "personal.savings": "Savings",
    "personal.setupBudget": "Setup your budget",
    "personal.quickEntry": "Quick entry & categorize",
    "personal.trackGoals": "Track your goals",
    "personal.financialInsights": "View financial insights",
    "personal.remaining": "Remaining",
    "personal.noneUntracked": "None (Untracked)",
    "personal.expenseAdded": "Expense added & account updated!",
    "personal.incomeAdded": "Income added & account updated!",
    "personal.invalidAmount": "Please enter a valid amount",
    "personal.logFailed": "Failed to log",

    // Budgets
    "budgets.title": "Category Budgets",
    "budgets.addCategory": "Add Budget Category",
    "budgets.noCategories": "No budget categories setup yet.",
    "budgets.modalTitle": "Add Budget Category",
    "budgets.categoryName": "Category Name",
    "budgets.categoryPlaceholder": "e.g., Food, Clothing, Hang-out",
    "budgets.amount": "Amount ($)",
    "budgets.frequency": "Frequency",
    "budgets.daily": "Daily",
    "budgets.weekly": "Weekly",
    "budgets.monthly": "Monthly",
    "budgets.yearly": "Yearly",
    "budgets.startDate": "Start Date",
    "budgets.allocated": "Allocated",
    "budgets.over": "Over by",
    "budgets.left": "left",
    "budgets.spent": "Spent",
    "budgets.trackingSince": "Tracking since",
    "budgets.added": "Budget category added!",
    "budgets.failed": "Failed to setup budget",

    // Personal Expenses
    "expenses.title": "Personal Expenses",
    "expenses.quickEntry": "Quick Expense Entry",
    "expenses.amount": "Amount ($)",
    "expenses.quickNote": "Quick Note",
    "expenses.saveNow": "Save Now",
    "expenses.allExpenses": "All Expenses",
    "expenses.noExpenses": "No expenses yet.",
    "expenses.noNote": "No note",
    "expenses.selectCategory": "Select...",
    "expenses.miscNotBudgeted": "Misc (Not Budgeted)",
    "expenses.addNewCategory": "+ Add New Category",
    "expenses.recorded": "Expense recorded!",
    "expenses.saveFailed": "Failed to save expense",
    "expenses.categorizeFailed": "Failed to categorize",
    "expenses.newCategoryName": "Enter new category name:",
    "expenses.budgetLimit": "Enter monthly budget limit for",
    "expenses.budgetCreated": "Budget created & expense categorized!",

    // Savings
    "savings.title": "Savings Goals",
    "savings.newGoal": "New Goal",
    "savings.noGoals": "No savings goals yet.",
    "savings.modalTitle": "Create Savings Goal",
    "savings.targetAmount": "Total Target Amount ($)",
    "savings.thresholdAmount": "Threshold to save per period ($)",
    "savings.frequency": "Frequency",
    "savings.daily": "Daily",
    "savings.weekly": "Weekly",
    "savings.monthly": "Monthly",
    "savings.goal": "Savings Goal",
    "savings.schedule": "Save",
    "savings.progress": "Progress",
    "savings.addFunds": "Add Funds to Savings",
    "savings.enterAmount": "Enter amount to add:",
    "savings.added": "Funds added!",
    "savings.created": "Goal created!",
    "savings.failed": "Failed to add funds",
    "savings.createFailed": "Failed",

    // Reports
    "reports.title": "Personal Finance Report",
    "reports.generating": "Generating report...",
    "reports.budgetPerformance": "Budget Performance",
    "reports.totalBudget": "Total Budget",
    "reports.totalSpent": "Total Spent",
    "reports.remaining": "Remaining",
    "reports.activePeriods": "Active Budget Periods:",
    "reports.expensesByCategory": "Expenses by Category",
    "reports.noExpenses": "No expenses recorded yet.",
    "reports.appreciative":
      "Excellent job! You are managing your budget perfectly.",
    "reports.inspiring": "You are getting close to your limit. Keep pushing!",
    "reports.complaining":
      "You have exceeded your budget. Please review your expenses.",
    "reports.totalIncome": "Total Income",
    "reports.totalSavings": "Total Savings",
    "reports.netWorth": "Net Worth",
    "reports.monthlyBreakdown": "Monthly Income vs Expense",
    "reports.budgetBreakdown": "Budget Breakdown",
    "reports.noBudgets": "No budgets setup yet.",
    "reports.budgetVsSpent": "Budget vs Spent",
    "reports.forecastTitle": "30-Day Cash Flow Forecast",
    "reports.dailyAvg": "Daily Avg",
    "reports.projectedBalance": "Projected Balance",
    "reports.projectedAfter30": "Projected balance after 30 days",
    "reports.accountsBreakdown": "Accounts Overview",
    "reports.totalAccountBalance": "Total Account Balance",

    // Accounts
    "accounts.title": "Accounts",
    "accounts.manage": "Manage your accounts & transfers",
    "accounts.totalBalance": "Total Balance",
    "accounts.count": "accounts",
    "accounts.newAccount": "New Account",
    "accounts.transfer": "Transfer",
    "accounts.transferring": "Transferring...",
    "accounts.createTitle": "Create Account",
    "accounts.transferTitle": "Transfer Money",
    "accounts.accountName": "Account Name",
    "accounts.namePlaceholder": "e.g., Savings, Checking, Cash",
    "accounts.initialBalance": "Initial Balance ($)",
    "accounts.fromAccount": "From Account",
    "accounts.toAccount": "To Account",
    "accounts.transferAmount": "Amount ($)",
    "accounts.transferNote": "Note (Optional)",
    "accounts.selectAccount": "Select account...",
    "accounts.noAccounts": "No accounts yet. Create one to start tracking.",
    "accounts.createdAt": "Created",
    "accounts.transferHistory": "Transfer History",
    "accounts.transferSuccess": "Transfer successful!",
    "accounts.transferFailed": "Transfer failed",
    "accounts.created": "Account created!",
    "accounts.createFailed": "Failed to create account",
    "accounts.deleted": "Account deleted",
    "accounts.deleteFailed": "Failed to delete account",
    "accounts.confirmDelete": "Are you sure you want to delete this account?",
    "accounts.fillAllFields": "Please fill all required fields",
    "accounts.sameAccount": "Cannot transfer to the same account",
    "expenses.account": "Account",
    "expenses.editExpense": "Edit Expense",
    "expenses.updated": "Expense updated!",
    "expenses.category": "Category",
    "expenses.insufficientBalance": "Insufficient balance for this amount",

    // Companies
    "companies.title": "Your Companies",
    "companies.newCompany": "New Company",
    "companies.modalTitle": "Create New Company",
    "companies.name": "Company Name",
    "companies.industry": "Industry (Optional)",
    "companies.generalBusiness": "General Business",
    "companies.staffCount": "Staff",
    "companies.expensesCount": "Expenses",
    "companies.created": "Company created successfully!",
    "companies.createFailed": "Failed to create company",
    "companies.fetchFailed": "Failed to fetch companies",

    // Notifications
    "notifications.title": "Notifications & Alerts",
    "notifications.empty": "No notifications.",
    "notifications.markRead": "Mark as read",
    "notifications.loadFailed": "Failed to load notifications",
    "notifications.updateFailed": "Failed to update notification",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.create": "Create",
    "common.creating": "Creating...",
    "common.saving": "Saving...",
    "common.daily": "Daily",
    "common.weekly": "Weekly",
    "common.monthly": "Monthly",
    "common.yearly": "Yearly",
  },
  am: {
    // Layout & Nav
    "nav.dashboard": "ዳሽቦርድ",
    "nav.personal": "የግል ፋይናንስ",
    "nav.companies": "ኩባንያዎች",
    "nav.notifications": "ማሳወቂያዎች",
    "nav.logout": "ውጣ",
    "nav.overview": "አጠቃላይ እይታ",
    "nav.incomes": "ገቢዎች",
    "nav.expenses": "ወጪዎች",
    "nav.staff": "ሰራተኞች",
    "nav.employees": "ተቀጣሪዎች",
    "nav.projects": "ፕሮጀክቶች",
    "nav.machineries": "ማሽኖች",
    "nav.store": "ማከማቻ",
    "nav.reports": "ሪፖርቶች",
    "header.welcome": "እንኳን ደህና መጡ",

    // Login
    "login.title": "FinSync",
    "login.subtitle": "ወደ መለያዎ ይግቡ",
    "login.email": "የኢሜይል አድራሻ",
    "login.password": "የይለፍ ቃል",
    "login.submit": "ይግቡ",
    "login.loading": "በመግባት ላይ...",
    "login.noAccount": "መለያ የሎትም? ይመዝገቡ",
    "login.welcomeBack": "እንኳን ደህና መጡ!",
    "login.failed": "መግባት አልተሳካም",

    // Register
    "register.title": "የባለቤት መለያ ይፍጠሩ",
    "register.subtitle": "ህይወትዎን እና ንግድዎን ማስተዳደር ይጀምሩ",
    "register.name": "ሙሉ ስም",
    "register.email": "የኢሜይል አድራሻ",
    "register.password": "የይለፍ ቃል",
    "register.submit": "ይመዝገቡ",
    "register.loading": "በመፍጠር ላይ...",
    "register.haveAccount": "አስቀድመው መለያ አለዎት? ይግቡ",
    "register.success": "መለያ በተሳካ ሁኔታ ተፈጥሯል!",
    "register.failed": "ምዝገባ አልተሳካም",

    // Landing
    "landing.title": "FinSync መተግበሪያ እየሰራ ነው!",
    "landing.subtitle": "ይህን ካዩ፣ ማሳያው እየሰራ ነው።",
    "landing.goLogin": "ወደ መግቢያ ይሂዱ",

    // Dashboard Overview
    "overview.title": "አጠቃላይ እይታ",
    "overview.personalFinance": "የግል ፋይናንስ",
    "overview.personalDesc": "ዕለታዊ በጀቶችዎን፣ ወጪዎችዎን እና ቁጠባ ግቦችዎን ይከታተሉ።",
    "overview.goPersonal": "ወደ የግል ፋይናንስ ይሂዱ →",
    "overview.businessOps": "የንግድ ስራዎች",
    "overview.businessDesc": "ኩባንያዎችን፣ ሰራተኞችን፣ ገቢዎችን እና ወጪዎችን ያስተዳድሩ።",
    "overview.goCompanies": "ኩባንያዎችን ያስተዳድሩ →",
    "overview.yourTasks": "የእርስዎ ተግባራት",
    "overview.staffWelcome":
      "እንኳን ደህና መጡ! ለእርስዎ የተመደቡትን ተግባራት ለማሰስ ምናሌውን ይጠቀሙ።",

    // Personal Hub
    "personal.title": "የግል ፋይናንስ",
    "personal.quickAdd": "ፈጣን መዝገብ",
    "personal.amount": "መጠን ($)",
    "personal.category": "ምድብ",
    "personal.account": "ሂሳብ",
    "personal.note": "ማስታወሻ (አማራጭ)",
    "personal.addExpense": "እንደ ወጪ ጨምር",
    "personal.addIncome": "እንደ ገቢ ጨምር",
    "personal.budgets": "በጀቶች",
    "personal.savings": "ቁጠባዎች",
    "personal.setupBudget": "በጀትዎን ያዘጋጁ",
    "personal.quickEntry": "ፈጣን ምዝገባ እና ምደባ",
    "personal.trackGoals": "ግቦችዎን ይከታተሉ",
    "personal.financialInsights": "የፋይናንስ ግንዛቤዎችን ይመልከቱ",
    "personal.remaining": "ቀሪ",
    "personal.noneUntracked": "ምንም (ያልተከታተለ)",
    "personal.expenseAdded": "ወጪ ተጨምሯል እና ሂሳብ ተዘምኗል!",
    "personal.incomeAdded": "ገቢ ተጨምሯል እና ሂሳብ ተዘምኗል!",
    "personal.invalidAmount": "እባክዎ ትክክለኛ መጠን ያስገቡ",
    "personal.logFailed": "መመዝገብ አልተሳካም",

    // Budgets
    "budgets.title": "የምድብ በጀቶች",
    "budgets.addCategory": "የበጀት ምድብ ጨምር",
    "budgets.noCategories": "እስካሁን ምንም የበጀት ምድቦች አልተዘጋጁም።",
    "budgets.modalTitle": "የበጀት ምድብ ጨምር",
    "budgets.categoryName": "የምድብ ስም",
    "budgets.categoryPlaceholder": "ለምሳሌ፦ ምግብ፣ ልብስ፣ መዝናኛ",
    "budgets.amount": "መጠን ($)",
    "budgets.frequency": "ድግግሞሽ",
    "budgets.daily": "ዕለታዊ",
    "budgets.weekly": "ሳምንታዊ",
    "budgets.monthly": "ወርሃዊ",
    "budgets.yearly": "ዓመታዊ",
    "budgets.startDate": "የመጀመሪያ ቀን",
    "budgets.allocated": "የተመደበ",
    "budgets.over": "አልፏል በ",
    "budgets.left": "ቀሪ",
    "budgets.spent": "የወጣ",
    "budgets.trackingSince": "ከዚህ ጀምሮ ክትትል",
    "budgets.added": "የበጀት ምድብ ተጨምሯል!",
    "budgets.failed": "በጀት ማዘጋጀት አልተሳካም",

    // Personal Expenses
    "expenses.title": "የግል ወጪዎች",
    "expenses.quickEntry": "ፈጣን ወጪ ምዝገባ",
    "expenses.amount": "መጠን ($)",
    "expenses.quickNote": "ፈጣን ማስታወሻ",
    "expenses.saveNow": "አሁን አስቀምጥ",
    "expenses.allExpenses": "ሁሉም ወጪዎች",
    "expenses.noExpenses": "እስካሁን ምንም ወጪ የለም።",
    "expenses.noNote": "ማስታወሻ የለም",
    "expenses.selectCategory": "ምረጥ...",
    "expenses.miscNotBudgeted": "ልዩ (ያልተመደበ)",
    "expenses.addNewCategory": "+ አዲስ ምድብ ጨምር",
    "expenses.recorded": "ወጪ ተመዝግቧል!",
    "expenses.saveFailed": "ወጪ ማስቀመጥ አልተሳካም",
    "expenses.categorizeFailed": "ምደባ አልተሳካም",
    "expenses.newCategoryName": "አዲስ የምድብ ስም ያስገቡ:",
    "expenses.budgetLimit": "ወርሃዊ የበጀት ገደብ ያስገቡ ለ",
    "expenses.budgetCreated": "በጀት ተፈጥሯል እና ወጪ ተመድቧል!",

    // Savings
    "savings.title": "የቁጠባ ግቦች",
    "savings.newGoal": "አዲስ ግብ",
    "savings.noGoals": "እስካሁን ምንም የቁጠባ ግቦች የሉም።",
    "savings.modalTitle": "የቁጠባ ግብ ይፍጠሩ",
    "savings.targetAmount": "ጠቅላላ የታለመ መጠን ($)",
    "savings.thresholdAmount": "በየወቅቱ የሚቆጠብ መጠን ($)",
    "savings.frequency": "ድግግሞሽ",
    "savings.daily": "ዕለታዊ",
    "savings.weekly": "ሳምንታዊ",
    "savings.monthly": "ወርሃዊ",
    "savings.goal": "የቁጠባ ግብ",
    "savings.schedule": "ያጠራቅሙ",
    "savings.progress": "ሂደት",
    "savings.addFunds": "ገንዘብ ወደ ቁጠባ ጨምር",
    "savings.enterAmount": "የሚጨምሩትን መጠን ያስገቡ:",
    "savings.added": "ገንዘብ ተጨምሯል!",
    "savings.created": "ግብ ተፈጥሯል!",
    "savings.failed": "ገንዘብ ማከል አልተሳካም",
    "savings.createFailed": "አልተሳካም",

    // Reports
    "reports.title": "የግል ፋይናንስ ሪፖርት",
    "reports.generating": "ሪፖርት በማመንጨት ላይ...",
    "reports.budgetPerformance": "የበጀት አፈጻጸም",
    "reports.totalBudget": "ጠቅላላ በጀት",
    "reports.totalSpent": "ጠቅላላ የወጣ",
    "reports.remaining": "ቀሪ",
    "reports.activePeriods": "ንቁ የበጀት ወቅቶች፦",
    "reports.expensesByCategory": "ወጪዎች በምድብ",
    "reports.noExpenses": "እስካሁን ምንም ወጪ አልተመዘገበም።",
    "reports.appreciative": "በጣም ጥሩ ስራ! በጀትዎን በትክክል እያስተዳደሩ ነው።",
    "reports.inspiring": "ወደ ገደብዎ እየተቃረቡ ነው። ይቀጥሉ!",
    "reports.complaining": "ከበጀትዎ አልፈዋል። እባክዎ ወጪዎችዎን ይገምግሙ።",
    "reports.totalIncome": "ጠቅላላ ገቢ",
    "reports.totalSavings": "ጠቅላላ ቁጠባ",
    "reports.netWorth": "የተጣራ ዋጋ",
    "reports.monthlyBreakdown": "ወርሃዊ ገቢ ከወጪ ጋር",
    "reports.budgetBreakdown": "የበጀት ዝርዝር",
    "reports.noBudgets": "እስካሁን ምንም በጀት አልተዘጋጀም።",
    "reports.budgetVsSpent": "በጀት ከወጣ ጋር",
    "reports.forecastTitle": "የ30-ቀን የገንዘብ ፍሰት ትንበያ",
    "reports.dailyAvg": "ዕለታዊ አማካይ",
    "reports.projectedBalance": "የተተነበየ ቀሪ ሂሳብ",
    "reports.projectedAfter30": "ከ30 ቀናት በኋላ የሚጠበቀው ቀሪ ሂሳብ",
    "reports.accountsBreakdown": "የሂሳቦች አጠቃላይ እይታ",
    "reports.totalAccountBalance": "ጠቅላላ የሂሳብ ቀሪ",

    // Accounts
    "accounts.title": "ሂሳቦች",
    "accounts.manage": "ሂሳቦችዎን እና ዝውውሮችዎን ያስተዳድሩ",
    "accounts.totalBalance": "ጠቅላላ ቀሪ ሂሳብ",
    "accounts.count": "ሂሳቦች",
    "accounts.newAccount": "አዲስ ሂሳብ",
    "accounts.transfer": "ዝውውር",
    "accounts.transferring": "በማዛወር ላይ...",
    "accounts.createTitle": "ሂሳብ ይፍጠሩ",
    "accounts.transferTitle": "ገንዘብ ያዛውሩ",
    "accounts.accountName": "የሂሳብ ስም",
    "accounts.namePlaceholder": "ለምሳሌ፦ ቁጠባ፣ ቼኪንግ፣ ጥሬ ገንዘብ",
    "accounts.initialBalance": "የመጀመሪያ ቀሪ ሂሳብ ($)",
    "accounts.fromAccount": "ከየትኛው ሂሳብ",
    "accounts.toAccount": "ወደ የትኛው ሂሳብ",
    "accounts.transferAmount": "መጠን ($)",
    "accounts.transferNote": "ማስታወሻ (አማራጭ)",
    "accounts.selectAccount": "ሂሳብ ይምረጡ...",
    "accounts.noAccounts": "እስካሁን ምንም ሂሳብ የለም። ለመጀመር አንድ ይፍጠሩ።",
    "accounts.createdAt": "የተፈጠረበት",
    "accounts.transferHistory": "የዝውውር ታሪክ",
    "accounts.transferSuccess": "ዝውውሩ ተሳክቷል!",
    "accounts.transferFailed": "ዝውውሩ አልተሳካም",
    "accounts.created": "ሂሳብ ተፈጥሯል!",
    "accounts.createFailed": "ሂሳብ መፍጠር አልተሳካም",
    "accounts.deleted": "ሂሳብ ተሰርዟል",
    "accounts.deleteFailed": "ሂሳብ መሰረዝ አልተሳካም",
    "accounts.confirmDelete": "ይህን ሂሳብ መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?",
    "accounts.fillAllFields": "እባክዎ ሁሉንም አስፈላጊ መስኮች ይሙሉ",
    "accounts.sameAccount": "ወደ ተመሳሳይ ሂሳብ ማዛወር አይቻልም",
    "expenses.account": "ሂሳብ",
    "expenses.editExpense": "ወጪ አስተካክል",
    "expenses.updated": "ወጪ ተዘምኗል!",
    "expenses.category": "ምድብ",
    "expenses.insufficientBalance": "ለዚህ መጠን በቂ ቀሪ ሂሳብ የለም",

    // Companies
    "companies.title": "የእርስዎ ኩባንያዎች",
    "companies.newCompany": "አዲስ ኩባንያ",
    "companies.modalTitle": "አዲስ ኩባንያ ይፍጠሩ",
    "companies.name": "የኩባንያ ስም",
    "companies.industry": "የኢንዱስትሪ አይነት (አማራጭ)",
    "companies.generalBusiness": "አጠቃላይ ንግድ",
    "companies.staffCount": "ሰራተኞች",
    "companies.expensesCount": "ወጪዎች",
    "companies.created": "ኩባንያ በተሳካ ሁኔታ ተፈጥሯል!",
    "companies.createFailed": "ኩባንያ መፍጠር አልተሳካም",
    "companies.fetchFailed": "ኩባንያዎችን ማምጣት አልተሳካም",

    // Notifications
    "notifications.title": "ማሳወቂያዎች እና ማንቂያዎች",
    "notifications.empty": "ምንም ማሳወቂያ የለም።",
    "notifications.markRead": "እንደተነበበ ምልክት አድርግ",
    "notifications.loadFailed": "ማሳወቂያዎችን መጫን አልተሳካም",
    "notifications.updateFailed": "ማሳወቂያ ማዘመን አልተሳካም",

    // Common
    "common.save": "አስቀምጥ",
    "common.cancel": "ይቅር",
    "common.delete": "ሰርዝ",
    "common.edit": "አስተካክል",
    "common.add": "ጨምር",
    "common.create": "ፍጠር",
    "common.creating": "በመፍጠር ላይ...",
    "common.saving": "በማስቀመጥ ላይ...",
    "common.daily": "ዕለታዊ",
    "common.weekly": "ሳምንታዊ",
    "common.monthly": "ወርሃዊ",
    "common.yearly": "ዓመታዊ",
  },
};

export const useLangStore = create<LangState>()(
  persist(
    (set, get) => ({
      lang: "en",
      setLang: (lang) => set({ lang }),
      t: (key) => {
        const lang = get().lang;
        return translations[lang]?.[key] || key;
      },
    }),
    {
      name: "finsync-lang",
    },
  ),
);
