import { EmploymentType, PrismaClient } from '@prisma/client';
import { SeedContext, daysAgo } from './utils';

interface EmployeeData {
  key: string;
  companyKey: string;
  name: string;
  employmentType: EmploymentType;
  wage: number;
  nextPayDate: number;
}

const EMPLOYEES: EmployeeData[] = [
  {
    key: 'buildco_carlos',
    companyKey: 'buildco',
    name: 'Carlos Ruiz',
    employmentType: EmploymentType.PERMANENT,
    wage: 4200,
    nextPayDate: -5,
  },
  {
    key: 'buildco_liam',
    companyKey: 'buildco',
    name: "Liam O'Connor",
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 65,
    nextPayDate: -1,
  },
  {
    key: 'buildco_yusuf',
    companyKey: 'buildco',
    name: 'Yusuf Ahmed',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 70,
    nextPayDate: -1,
  },
  {
    key: 'buildco_miguel',
    companyKey: 'buildco',
    name: 'Miguel Santos',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 60,
    nextPayDate: -2,
  },
  {
    key: 'buildco_raj',
    companyKey: 'buildco',
    name: 'Raj Patel',
    employmentType: EmploymentType.PERMANENT,
    wage: 3800,
    nextPayDate: -5,
  },
  {
    key: 'buildco_svetlana',
    companyKey: 'buildco',
    name: 'Svetlana Ivanova',
    employmentType: EmploymentType.PERMANENT,
    wage: 3500,
    nextPayDate: -5,
  },
  {
    key: 'buildco_james_o',
    companyKey: 'buildco',
    name: 'James Okonkwo',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 75,
    nextPayDate: -3,
  },
  {
    key: 'buildco_chen_wei',
    companyKey: 'buildco',
    name: 'Chen Wei',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 65,
    nextPayDate: 0,
  },
  {
    key: 'buildco_marie',
    companyKey: 'buildco',
    name: 'Marie Dupont',
    employmentType: EmploymentType.PERMANENT,
    wage: 4500,
    nextPayDate: -5,
  },
  {
    key: 'buildco_david_k',
    companyKey: 'buildco',
    name: 'David Kim',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 55,
    nextPayDate: -1,
  },
  {
    key: 'buildco_tony',
    companyKey: 'buildco',
    name: 'Tony Moretti',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 80,
    nextPayDate: -2,
  },
  {
    key: 'buildco_anh',
    companyKey: 'buildco',
    name: 'Anh Nguyen',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 60,
    nextPayDate: 0,
  },
  {
    key: 'horizon_mark',
    companyKey: 'horizon',
    name: 'Mark Johnson',
    employmentType: EmploymentType.PERMANENT,
    wage: 5500,
    nextPayDate: -3,
  },
  {
    key: 'horizon_linda',
    companyKey: 'horizon',
    name: 'Linda Chen',
    employmentType: EmploymentType.PERMANENT,
    wage: 4200,
    nextPayDate: -3,
  },
  {
    key: 'horizon_robert',
    companyKey: 'horizon',
    name: 'Robert Williams',
    employmentType: EmploymentType.PERMANENT,
    wage: 3800,
    nextPayDate: -3,
  },
  {
    key: 'horizon_patricia',
    companyKey: 'horizon',
    name: 'Patricia Garcia',
    employmentType: EmploymentType.PERMANENT,
    wage: 3500,
    nextPayDate: -3,
  },
  {
    key: 'horizon_kevin',
    companyKey: 'horizon',
    name: 'Kevin Brown',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 85,
    nextPayDate: -1,
  },
  {
    key: 'horizon_sandra',
    companyKey: 'horizon',
    name: 'Sandra Lee',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 90,
    nextPayDate: -1,
  },
  {
    key: 'green_pedro',
    companyKey: 'greenvalley',
    name: 'Pedro Gonzalez',
    employmentType: EmploymentType.PERMANENT,
    wage: 3200,
    nextPayDate: -4,
  },
  {
    key: 'green_elena',
    companyKey: 'greenvalley',
    name: 'Elena Kowalczyk',
    employmentType: EmploymentType.PERMANENT,
    wage: 2800,
    nextPayDate: -4,
  },
  {
    key: 'green_jamal',
    companyKey: 'greenvalley',
    name: 'Jamal Hassan',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 55,
    nextPayDate: -2,
  },
  {
    key: 'green_maria_f',
    companyKey: 'greenvalley',
    name: 'Maria Fernandez',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 50,
    nextPayDate: -1,
  },
  {
    key: 'green_tomas',
    companyKey: 'greenvalley',
    name: 'Tomas Novak',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 60,
    nextPayDate: -2,
  },
  {
    key: 'green_akeem',
    companyKey: 'greenvalley',
    name: 'Akeem Osei',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 55,
    nextPayDate: 0,
  },
  {
    key: 'urban_sophie',
    companyKey: 'urban_threads',
    name: 'Sophie Martin',
    employmentType: EmploymentType.PERMANENT,
    wage: 3200,
    nextPayDate: -5,
  },
  {
    key: 'urban_jack',
    companyKey: 'urban_threads',
    name: 'Jack Turner',
    employmentType: EmploymentType.PERMANENT,
    wage: 2500,
    nextPayDate: -5,
  },
  {
    key: 'urban_olivia',
    companyKey: 'urban_threads',
    name: 'Olivia Park',
    employmentType: EmploymentType.PERMANENT,
    wage: 2400,
    nextPayDate: -5,
  },
  {
    key: 'urban_noah',
    companyKey: 'urban_threads',
    name: 'Noah Williams',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 80,
    nextPayDate: -1,
  },
  {
    key: 'urban_emma_r',
    companyKey: 'urban_threads',
    name: 'Emma Rodriguez',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 75,
    nextPayDate: 0,
  },
  {
    key: 'techmfg_dr_zhang',
    companyKey: 'tech_mfg',
    name: 'Dr. Wei Zhang',
    employmentType: EmploymentType.PERMANENT,
    wage: 8500,
    nextPayDate: -3,
  },
  {
    key: 'techmfg_priya',
    companyKey: 'tech_mfg',
    name: 'Priya Sharma',
    employmentType: EmploymentType.PERMANENT,
    wage: 5500,
    nextPayDate: -3,
  },
  {
    key: 'techmfg_tommy',
    companyKey: 'tech_mfg',
    name: 'Tommy Lim',
    employmentType: EmploymentType.PERMANENT,
    wage: 4000,
    nextPayDate: -3,
  },
  {
    key: 'techmfg_sarah_j',
    companyKey: 'tech_mfg',
    name: 'Sarah Johnson',
    employmentType: EmploymentType.PERMANENT,
    wage: 3800,
    nextPayDate: -3,
  },
  {
    key: 'techmfg_mike_r',
    companyKey: 'tech_mfg',
    name: 'Mike Rodriguez',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 95,
    nextPayDate: -1,
  },
  {
    key: 'techmfg_anna_l',
    companyKey: 'tech_mfg',
    name: 'Anna Lindberg',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 90,
    nextPayDate: 0,
  },
  {
    key: 'fresheats_chef_marco',
    companyKey: 'fresh_eats',
    name: 'Chef Marco Rossi',
    employmentType: EmploymentType.PERMANENT,
    wage: 5200,
    nextPayDate: -2,
  },
  {
    key: 'fresheats_sous_chef',
    companyKey: 'fresh_eats',
    name: 'Yuki Tanaka',
    employmentType: EmploymentType.PERMANENT,
    wage: 3800,
    nextPayDate: -2,
  },
  {
    key: 'fresheats_server_1',
    companyKey: 'fresh_eats',
    name: 'Jake Cooper',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 70,
    nextPayDate: -1,
  },
  {
    key: 'fresheats_server_2',
    companyKey: 'fresh_eats',
    name: 'Mia Thompson',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 70,
    nextPayDate: 0,
  },
  {
    key: 'fresheats_dishwasher',
    companyKey: 'fresh_eats',
    name: 'Carlos Mendez',
    employmentType: EmploymentType.DAILY_LABORER,
    wage: 55,
    nextPayDate: -1,
  },
];

export async function seedEmployees(
  prisma: PrismaClient,
  ctx: SeedContext,
): Promise<void> {
  console.log('👷 Seeding Employees...');

  for (const emp of EMPLOYEES) {
    const created = await prisma.employee.create({
      data: {
        companyId: ctx.companies[emp.companyKey],
        name: emp.name,
        employmentType: emp.employmentType,
        wage: emp.wage,
        nextPayDate: daysAgo(-emp.nextPayDate),
      },
    });
    ctx.employees[emp.key] = created.id;
  }

  console.log(`   ✅ Created ${EMPLOYEES.length} employees`);
}
